---
- name: Deploy Network Commands
  hosts: network_devices
  gather_facts: false
  tasks:
    - name: Execute Cisco commands
      cisco.ios.ios_command:
        commands: "{{ commands }}"
      register: command_output
      when: device_type == "cisco"

    - name: Execute Huawei commands
      huawei.vrp.vrp_command:
        commands: "{{ commands }}"
      register: command_output
      when: device_type == "huawei"

    - name: Show command outputs
      debug:
        var: command_output