- name: Deploy Network Commands
  hosts: network_devices
  gather_facts: false
  tasks:
  - name: Run Cisco commands
    cisco.ios.ios_command:
      commands: '{{ commands }}'
    register: command_output
    when: device_type == 'cisco'
  - name: Run Huawei commands
    community.network.ce_command:
      commands: '{{ commands }}'
    register: command_output
    when: device_type == 'huawei'
  - name: "Afficher les r\xE9sultats"
    debug:
      var: command_output
