# Generated by Django 5.0.6 on 2025-05-03 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('routing', 'Routing'), ('switching', 'Switching'), ('security', 'Security'), ('management', 'Management'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Command Action',
                'verbose_name_plural': 'Command Actions',
                'indexes': [models.Index(fields=['category', 'title'], name='commandes_c_categor_661d6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommandParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('validation_regex', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Command Parameter',
                'verbose_name_plural': 'Command Parameters',
                'indexes': [models.Index(fields=['name'], name='commandes_c_name_2589fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Constructor',
                'verbose_name_plural': 'Constructors',
                'indexes': [models.Index(fields=['name'], name='commandes_c_name_c9b166_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommandVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.TextField()),
                ('example', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='commandes.commandaction')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='commandes.constructor')),
            ],
            options={
                'verbose_name': 'Command Variant',
                'verbose_name_plural': 'Command Variants',
                'indexes': [models.Index(fields=['action', 'constructor'], name='commandes_c_action__be960f_idx')],
                'unique_together': {('action', 'constructor')},
            },
        ),
        migrations.CreateModel(
            name='CommandAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(max_length=255)),
                ('full_command', models.CharField(max_length=255)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='commandes.constructor')),
            ],
            options={
                'verbose_name': 'Command Alias',
                'verbose_name_plural': 'Command Aliases',
                'indexes': [models.Index(fields=['constructor', 'alias_text'], name='commandes_c_constru_ec43ce_idx')],
                'unique_together': {('constructor', 'alias_text')},
            },
        ),
    ]
